include ../Makefile.defs

.DEFAULT_GOAL:=all


mycat: q2/mycat.c setup
	$(CC) $(CCFLAGS) q2/mycat.c -o $(BIN)/mycat

chcase: q3/chcase.c setup
	$(CC) $(CCFLAGS) q3/chcase.c -o $(BIN)/chcase

mycp: q4/mycp.c setup
	$(CC) $(CCFLAGS) q4/mycp.c -o $(BIN)/mycp

mywc: q5/mywc.c setup
	$(CC) $(CCFLAGS) q5/mywc.c -o $(BIN)/mywc

mygrep: q6/mygrep.c setup
	$(CC) $(CCFLAGS) q6/mygrep.c -o $(BIN)/mygrep